# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets: 
        squared_thumb: 
            quality: 90
            filters:
                thumbnail  : { size : [300, 300], mode : outbound }
        squared_thumb_blog: 
            quality: 80
            filters:
                thumbnail  : { size : [250, 250], mode : outbound }
        thumb_home: 
            quality: 100
            filters:
                thumbnail  : { size : [250, 2git00], mode : outbound }
                    
        crop_filter: 
            filters:
                crop:
                    size: [1000, 1000]
                    start: [ 400 , 400 ]
        