# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "gd"

    filter_sets: 
        squared_thumb: 
            quality: 90
            filters:
                thumbnail  : { size : [300, 300], mode : outbound }
        squared_thumb_blog: 
            quality: 80
            filters:
                thumbnail  : { size : [250, 250], mode : outbound }
        thumb_home: 
            quality: 100
            filters:
                thumbnail  : { size : [280, 150], mode : outbound }
        thumb_home_last: 
            quality: 100
            filters:
                thumbnail  : { size : [600, 150], mode : outbound }
        scale_filter: 
            filters:
                scale:
                    dim: [1000, 1000]
                    
        