vich_uploader:
    db_driver: orm

    mappings:
       illustration_images:
           uri_prefix: '/uploads/illustration'
           upload_destination: '%kernel.project_dir%/public/uploads/illustration'
           namer: vich_uploader.namer_origname
       album_images:    
           uri_prefix: '/uploads/album'
           upload_destination: '%kernel.project_dir%/public/uploads/album'
           namer: vich_uploader.namer_origname
       slider_images:
           uri_prefix: '/uploads/album/slider'
           upload_destination: '%kernel.project_dir%/public/uploads/album/slider'
           namer: vich_uploader.namer_origname
       article_images:
           uri_prefix: '/uploads/article'
           upload_destination: '%kernel.project_dir%/public/uploads/article'
           namer: vich_uploader.namer_origname

           